#!/usr/bin/env bash
# =============================================================================
# setup.sh — One-command first-time server setup for Acumen Playbook
# Generates all secrets, writes .env, configures postgres/init.sql
# Usage: bash scripts/setup.sh
# Must be run from the project root (/opt/acumen-playbook/)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"
SQL_FILE="$ROOT_DIR/postgres/init.sql"

cd "$ROOT_DIR"

echo ""
echo "=============================================="
echo "  Acumen Playbook — First-Time Setup"
echo "=============================================="

# -----------------------------------------------------------------------
# Guard: Don't overwrite an existing .env
# -----------------------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  echo ""
  echo "  ⚠  A .env file already exists."
  read -r -p "  Overwrite it and regenerate all secrets? [y/N]: " CONFIRM
  if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
    echo "  Aborting. Your existing .env was not changed."
    exit 0
  fi
fi

echo ""
echo "  Generating random secrets..."

# -----------------------------------------------------------------------
# Generate all secret values
# -----------------------------------------------------------------------
gen() { openssl rand -base64 32; }
gen_hex() { openssl rand -hex 16; }

POSTGRES_ROOT_PASSWORD=$(gen)
STRAPI_DB_PASSWORD=$(gen)
WIKIJS_DB_PASSWORD=$(gen)
REDIS_PASSWORD=$(gen)
RABBITMQ_PASSWORD=$(gen)

APP_KEY1=$(gen)
APP_KEY2=$(gen)
APP_KEY3=$(gen)
APP_KEY4=$(gen)
APP_KEYS="${APP_KEY1},${APP_KEY2},${APP_KEY3},${APP_KEY4}"

API_TOKEN_SALT=$(gen)
ADMIN_JWT_SECRET=$(gen)
TRANSFER_TOKEN_SALT=$(gen)
JWT_SECRET=$(gen)

# -----------------------------------------------------------------------
# Prompt for domain (default: localhost for testing)
# -----------------------------------------------------------------------
echo ""
read -r -p "  Enter your domain name (press Enter for 'localhost'): " DOMAIN_INPUT
DOMAIN="${DOMAIN_INPUT:-localhost}"

# -----------------------------------------------------------------------
# Write .env file
# -----------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# =============================================================================
# Acumen Playbook — Generated by scripts/setup.sh on $(date -u -Iseconds)
# DO NOT COMMIT THIS FILE
# =============================================================================

# PostgreSQL
POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}

# Strapi Database
STRAPI_DB_NAME=acumen_strapi
STRAPI_DB_USER=strapi_user
STRAPI_DB_PASSWORD=${STRAPI_DB_PASSWORD}

# Wiki.js Database
WIKIJS_DB_NAME=acumen_wikijs
WIKIJS_DB_USER=wikijs_user
WIKIJS_DB_PASSWORD=${WIKIJS_DB_PASSWORD}

# Strapi 5 Security Keys
APP_KEYS=${APP_KEYS}
API_TOKEN_SALT=${API_TOKEN_SALT}
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
JWT_SECRET=${JWT_SECRET}

# Strapi API Token (fill in after first boot)
STRAPI_API_TOKEN=FILL_IN_AFTER_FIRST_BOOT

# Wiki.js API Token (fill in after first boot)
WIKIJS_API_TOKEN=FILL_IN_AFTER_FIRST_BOOT

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# RabbitMQ
RABBITMQ_USER=acumen_rabbit
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

# Caddy / Domain
DOMAIN=${DOMAIN}

# Sync Service
LOG_LEVEL=info
EOF

echo "  ✔  .env written"

# -----------------------------------------------------------------------
# Patch postgres/init.sql with the generated passwords
# -----------------------------------------------------------------------
# Replace any previous password values (handles re-runs)
sed -i "s|WITH PASSWORD '[^']*'; -- STRAPI|WITH PASSWORD '${STRAPI_DB_PASSWORD}'; -- STRAPI|g" "$SQL_FILE"
sed -i "s|WITH PASSWORD '[^']*'; -- WIKIJS|WITH PASSWORD '${WIKIJS_DB_PASSWORD}'; -- WIKIJS|g" "$SQL_FILE"

echo "  ✔  postgres/init.sql patched"
echo ""
echo "  Done! Everything is configured. Run:"
echo ""
echo "    docker compose build && docker compose up -d"
echo ""
echo "  After services are healthy, complete the setup:"
echo "    1. Open https://${DOMAIN}/strapi/admin  → Create admin, generate API token → paste into .env as STRAPI_API_TOKEN"
echo "    2. Open https://${DOMAIN}               → Complete Wiki.js setup, generate API token → paste into .env as WIKIJS_API_TOKEN"
echo "    3. docker compose up -d --no-deps sync-service"
echo ""
